# -*- coding: utf-8 -*-
"""exo5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rCKAn-GLPqKZPemawgsQC31NsKqs156K
"""

def somme_pairs(l):
  dim=len(l)
  s=0
  for i in range(dim):
    if l[i]%2==0:
      s=s+l[i]
  return s
l=[]
while True:

  while True:
    a=input("entrer un element de votre liste (nombre) : ")
    try :
     a=float(a)
     break
    except ValueError:
     print("entrer un chiffre svp")
  l.append(a)
  arret=input("voulez vous entrer un autre élément ?\ntapez n'importe quelle touche pour continuer OU N pour arreter")
  if arret=="N" or arret=="n":
    break
print("la somme des chiffres pairs est : ",somme_pairs(l))